### ISSUE TITLE
$is: Boolean support

### ISSUE THREAD

**Issue by jurajsimbs** [fogine/json-inspector#1]
I have 2 codes for checking boolean value in my data:
https://runkit.com/jurajsim/57b199bf4e962a1200532d58
first one is not working, second is
probably the reason is that $isBoolean is also accepting "true" and "false" as bool values - right?

**Comment by fogine** [comment]
Hello Juraj,

Simply, `$is` does not support `Boolean` / `"boolean"` parameter yet. You can see currently supported arguments [HERE](https://github.com/fogine/json-inspector/wiki/Assertions#is---data-type-list).

Difference would be that `$isBoolean` accepts also values: `"true"` / `"false"` (strings) while `$is: Boolean` will accept value of type `boolean` only.

[HERE](https://github.com/fogine/json-inspector/wiki/Assertions#likefilterobject) at bottom of the page is list of `keywords` which operate on strings only.

**Comment by jurajsimbs** [comment]
yes I was aware that it is not supported from sources. I was just curious if there was some purpose to it.
so its like I wrote
`
probably the reason is that $isBoolean is also accepting "true" and "false" as bool values - right?
`
all clear then. thx

**Comment by jurajsimbs** [comment]
hmm... no wait. As I am thinking about this. Shouldn't it throw an exception if I use unsupported type in `$is` ? like in my example:

```
var inspector = require("json-inspector");
var Validator = inspector.Validator;
var val = new Validator({
        field1: {
            $is: Boolean

        }
    }
);
var result = val.validate({aaa: 123, field1: true});
console.log('RESULT', result.success);
```

code that runs but result in wrong answer

**Comment by fogine** [comment]
Good point. It does throw. However the Exception gets lost - it's not properly propagated. I'll fix it, thanks for report !
